name: ci 
on:
  push:
    branches:
      - master 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # Add permission for GitHub Pages
      id-token: write   # Add permission for GitHub Pages deployment

    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git submodule update --init --recursive
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material "mkdocs-material[imaging]" mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-rss-plugin  mkdocs-static-i18n[material] python-dotenv openai pdfplumber python-docx
      # - run: pip install -r .github/scripts/requirements.txt
      - run: sudo apt-get install libcairo2-dev
      # - name: Prepare site
      #   run: |
      #     mkdir -p docs
      #     cp README.md docs/README.md
      #     cp README.zh.md docs/README.zh.md

      # - name: Create docs directory
      #   run: |
      #     mkdir -p site
      #     cp -r .github/*.yml ./

      - run: mkdocs gh-deploy --force

      # - name: Run publish script
      #   env:
      #     PUBLISHER_API_KEY: ${{ secrets.PUBLISHER_API_KEY }}
      #     PUBLISH_AS_DRAFT: 'true'  # Or 'false' if you want to publish directly
      #   run: |
      #     python .github/manage/publish.py
      
    
